import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.css';
import Header from "../components/header";
import axios from "axios";
import Head from "next/head";

const AppComponent = ({Component, pageProps, isAuth}) => {
    return (
        <>
            <Head>
                <title>Zunami</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/surfboard.svg"/>
            </Head>
            <Header/>
            <Component isAuth={isAuth} {...pageProps} />
        </>

    );
};

AppComponent.getInitialProps = async (appContext) => {
    // const token = localStorage.getItem("auth-token");
    try {
        await axios.get(process.env.NEXT_PUBLIC_SERVER_URL + '/auth/refresh-token',
            {
                headers: {
                    Authorization: '',
                }
            });
    }
    
    catch (e) {

    }

    let pageProps = {};

    const data = {}

    return {
        pageProps,
        ...data,
    };
};

export default AppComponent;
